---
add_plugin_period: true
always_refresh: true
changelog_nice_yaml: true
changelog_sort: version
changelog_filename_template: ../CHANGELOG.rst
changelog_filename_version_depth: 0
changes_file: changelog.yml
changes_format: combined
keep_fragments: true
flatmap: true
ignore_other_fragment_extensions: true
mention_ancestor: false
new_plugins_after_name: removed_features
notesdir: fragments
output_formats:
  - md
  - rst
prelude_section_name: release_summary
prelude_section_title: Release Summary
pre_release_tag_re: '(?P<pre_release>(?:[ab]|rc)+\d*)$'
release_tag_re: '(v(?:[\d.ab\-]|rc)+)'
sections:
- ['major_changes', 'Major Changes']
- ['minor_changes', 'Minor Changes']
- ['breaking_changes', 'Breaking Changes / Porting Guide']
- ['deprecated_features', 'Deprecated Features']
- ['removed_features', 'Removed Features (previously deprecated)']
- ['security_fixes', 'Security Fixes']
- ['bugfixes', 'Bugfixes']
- ['known_issues', 'Known Issues']
title: dettonville.utils
trivial_section_name: trivial
use_fqcn: true
