---
name: Publish Ansible Collection

concurrency:
  group: >-
    ${{ github.workflow }}-${{
      github.event.pull_request.number || github.sha
    }}
  cancel-in-progress: true

on: # yamllint disable-line rule:truthy
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  workflow_dispatch:
  push:
    branches:
      - main
      - stable-*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - stable-*
    tags:
      - "*"

jobs:
  lint:
    uses: ./.github/workflows/ansible-lint.yml # use the callable linters job to run tests
  sanity:
    uses: ./.github/workflows/ansible-test-sanity.yml # use the callable sanity job to run tests
  units:
    uses: ./.github/workflows/ansible-test-units.yml # use the callable units job to run tests
  publish:
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
      - sanity
      - units
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.lint.result }}',
          '${{ needs.sanity.result }}',
          '${{ needs.units.result }}'
          ]) == {'success'}"

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible passlib distlib

      - name: Create Collection Archive
        run: |
          ansible-galaxy collection build

      - name: Publish Collection to Galaxy
        run: |
          MODULE_VERSION=$(yq e '.version' galaxy.yml)
          MODULE_NAMESPACE=$(yq e '.namespace' galaxy.yml)
          MODULE_NAME=$(yq e '.name' galaxy.yml)
          echo "Module : [Namespace : $MODULE_NAMESPACE, Name : $MODULE_NAME, Version: $MODULE_VERSION]"
          ansible-galaxy collection publish $MODULE_NAMESPACE-$MODULE_NAME-$MODULE_VERSION.tar.gz --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY}}
